-- Phase 5: Reporting Upgrades

CREATE TABLE IF NOT EXISTS public.report_history (
    id bigint generated by default as identity primary key,
    company_id text references public.companies(company_id) on delete cascade not null,
    report_type text not null,
    status text default 'success',
    generated_at timestamptz default now() not null
);

CREATE TABLE IF NOT EXISTS public.scheduled_reports (
    id bigint generated by default as identity primary key,
    company_id text references public.companies(company_id) on delete cascade not null,
    frequency text default 'monthly' not null,
    recipient_emails jsonb default '[]'::jsonb not null,
    next_run_at timestamptz,
    is_active boolean default true,
    created_at timestamptz default now(),
    UNIQUE(company_id)
);

CREATE TABLE IF NOT EXISTS public.managed_reviews (
    id bigint generated by default as identity primary key,
    company_id text references public.companies(company_id) on delete cascade not null,
    month_year text not null,
    analyst_id text,
    vulnerable_plugins_note text,
    failed_hardening_note text,
    suspicious_logins_note text,
    status text default 'draft' not null,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    UNIQUE(company_id, month_year)
);

ALTER TABLE public.companies
ADD COLUMN IF NOT EXISTS whitelabel_logo_url text,
ADD COLUMN IF NOT EXISTS whitelabel_agency_name text,
ADD COLUMN IF NOT EXISTS whitelabel_footer_text text;

-- Enable RLS and setup policies
ALTER TABLE public.report_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scheduled_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.managed_reviews ENABLE ROW LEVEL SECURITY;

-- Grant permissions to roles
GRANT ALL ON public.report_history TO anon, authenticated, service_role;
GRANT ALL ON public.scheduled_reports TO anon, authenticated, service_role;
GRANT ALL ON public.managed_reviews TO anon, authenticated, service_role;

-- Allow reading own company's report history
CREATE POLICY "Users can read own report history" ON public.report_history
FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM user_profiles
    WHERE user_profiles.id = auth.uid()
    AND (user_profiles.company_id = report_history.company_id OR user_profiles.role = 'admin')
  )
);

-- Allow admins to insert report history
CREATE POLICY "Admins can insert report history" ON public.report_history
FOR ALL USING (
  EXISTS (
    SELECT 1 FROM user_profiles WHERE id = auth.uid() AND role = 'admin'
  )
);

-- Users can read own scheduled reports
CREATE POLICY "Users can read own scheduled reports" ON public.scheduled_reports
FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM user_profiles
    WHERE user_profiles.id = auth.uid()
    AND (user_profiles.company_id = scheduled_reports.company_id OR user_profiles.role = 'admin')
  )
);

-- Users can manage own scheduled reports
CREATE POLICY "Users can manage own scheduled reports" ON public.scheduled_reports
FOR ALL USING (
  EXISTS (
    SELECT 1 FROM user_profiles
    WHERE user_profiles.id = auth.uid()
    AND (user_profiles.company_id = scheduled_reports.company_id OR user_profiles.role = 'admin')
  )
);

-- Users can read own managed reviews
CREATE POLICY "Users can read own managed reviews" ON public.managed_reviews
FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM user_profiles
    WHERE user_profiles.id = auth.uid()
    AND (user_profiles.company_id = managed_reviews.company_id OR user_profiles.role = 'admin')
  )
);

-- Admins can manage all managed reviews
CREATE POLICY "Admins can manage managed reviews" ON public.managed_reviews
FOR ALL USING (
  EXISTS (
    SELECT 1 FROM user_profiles WHERE id = auth.uid() AND role = 'admin'
  )
);
